CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

CONFIG_LV_FONT_UNSCII_8=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_Z_MEM_POOL_SIZE=32768

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
